# Generated by Django 4.2.1 on 2023-05-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='img',
        ),
    ]
