# Generated by Django 4.2.1 on 2023-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapp', '0002_rename_image_movie_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='update/img')),
            ],
        ),
    ]
